# -*- coding: utf-8 -*-
"""bot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZlvkMpgPEtwdbSzBLHgRp1pgty55iTRK
"""

from telegram import Update
from telegram.ext import ApplicationBuilder, CommandHandler, ContextTypes
from retrieval import retrieve
from llm import generate_answer
from config import settings

history = {}

async def help_cmd(update: Update, ctx: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text(
        "/ask <query> - Ask question\n"
        "/summarize - Summarize last 3 queries\n"
        "/help - Help"
    )

async def ask_cmd(update: Update, ctx: ContextTypes.DEFAULT_TYPE):
    user = update.message.from_user.id
    query = " ".join(ctx.args)

    history.setdefault(user, [])
    history[user].append(query)
    history[user] = history[user][-3:]

    context, sources = retrieve(query)
    answer = generate_answer(query, context)
    reply = f"{answer}\n\nSources: {', '.join(sources)}"

    await update.message.reply_text(reply)

async def summarize_cmd(update: Update, ctx: ContextTypes.DEFAULT_TYPE):
    user = update.message.from_user.id
    if user not in history:
        return await update.message.reply_text("No history.")

    text = " ".join(history[user])
    summary = generate_answer("Summarize this text:", text)

    await update.message.reply_text(summary)

def run_bot():
    app = ApplicationBuilder().token(settings.TELEGRAM_BOT_TOKEN).build()
    app.add_handler(CommandHandler("help", help_cmd))
    app.add_handler(CommandHandler("ask", ask_cmd))
    app.add_handler(CommandHandler("summarize", summarize_cmd))
    app.run_polling()







