# -*- coding: utf-8 -*-
"""cache

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZlvkMpgPEtwdbSzBLHgRp1pgty55iTRK
"""

import os
import pickle
import hashlib
from config import settings

os.makedirs(settings.CACHE_DIR, exist_ok=True)

def _cache_path(key):
    hashed = hashlib.md5(key.encode("utf-8")).hexdigest()
    return os.path.join(settings.CACHE_DIR, f"{hashed}.pkl")

def save_cache(key, value):
    with open(_cache_path(key), "wb") as f:
        pickle.dump(value, f)

def load_cache(key):
    path = _cache_path(key)
    if os.path.exists(path):
        with open(path, "rb") as f:
            return pickle.load(f)
    return None







