# -*- coding: utf-8 -*-
"""config

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZlvkMpgPEtwdbSzBLHgRp1pgty55iTRK
"""

from pydantic import BaseModel
import os

class Settings(BaseModel):
    TELEGRAM_BOT_TOKEN: str = os.getenv("TELEGRAM_BOT_TOKEN", "YOUR_TELEGRAM_BOT_TOKEN")

    KB_FOLDER: str = "kb_docs"
    DB_PATH: str = "vector_db/kb_vectors.db"
    TABLE_NAME: str = "documents"
    EMBED_MODEL: str = "all-MiniLM-L6-v2"
    LLM_MODEL: str = "google/flan-t5-small"
    EMBED_DIM: int = 384
    CACHE_DIR: str = "cache"

settings = Settings()







