# -*- coding: utf-8 -*-
"""embedd

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZlvkMpgPEtwdbSzBLHgRp1pgty55iTRK
"""

from sentence_transformers import SentenceTransformer
import numpy as np
from config import EMBED_MODEL

class Embedder:
    def __init__(self):
        self.model = SentenceTransformer(EMBED_MODEL)

    def embed(self, text: str):
        return np.array(self.model.encode(text))







