# -*- coding: utf-8 -*-
"""knowledge_base

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZlvkMpgPEtwdbSzBLHgRp1pgty55iTRK
"""

import os
from chunk import split_into_chunks
from config import settings

def load_kb_documents():
    docs = {}
    for file in os.listdir(settings.KB_FOLDER):
        path = os.path.join(settings.KB_FOLDER, file)
        with open(path, "r", encoding="utf-8") as f:
            content = f.read()
            docs[file] = split_into_chunks(content)
    return docs







