# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZlvkMpgPEtwdbSzBLHgRp1pgty55iTRK
"""

from embedd import build_vector_db
from bot import run_bot

if __name__ == "__main__":
    build_vector_db(force=False)
    run_bot()







