# -*- coding: utf-8 -*-
"""utils

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZlvkMpgPEtwdbSzBLHgRp1pgty55iTRK
"""

from sentence_transformers import SentenceTransformer
from knowledge_base import load_kb_documents
from vector_db import add_vector, total_vectors
from config import settings
import os

# chunking and Embedding
def split_into_chunks(text, chunk_size=200):
    words = text.split()
    chunks = [" ".join(words[i:i + chunk_size]) for i in range(0, len(words), chunk_size)]
    return chunks

model = SentenceTransformer(settings.EMBED_MODEL)

def build_vector_db(force=False):
    if total_vectors() > 0 and not force:
        print("Vector DB already built. Skipping.")
        return

    print("Building vector DB...")
    docs = load_kb_documents()

    for file, chunks in docs.items():
        for i, chunk in enumerate(chunks):
            vec = model.encode(chunk)
            item_id = f"{file}_{i}"
            add_vector(
                item_id=item_id,
                vector=vec,
                payload={"text": chunk, "source": file}
            )

    print("Vector DB build complete!")







